spring.application.name=inciApp

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jwt.private.key=${PRIVATE_KEY}
spring.jwt.user.generator=${USER_GENERATOR}